kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-6553562a-c6c9-4aa4-b7d1-16c7c7341e6a
  namespace: portworx
  annotations:
    portworx.io/install-source: "https://install.portworx.com/3.2?operator=true&mc=false&kbver=1.30.11&ns=portworx&b=true&iop=6&s=%22size%3D150%22&pureSanType=ISCSI&ce=pure&c=px-cluster-6553562a-c6c9-4aa4-b7d1-16c7c7341e6a&stork=true&csi=true&tel=true&st=k8s"
spec:
  image: portworx/oci-monitor:3.2.3
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
    - size=150
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
  env:
  - name: PURE_FLASHARRAY_SAN_TYPE
    value: "ISCSI"
